language: node_js
node_js:
    - stable
branches:
    only:
        - source

install: npm install

before_script:
    - git config --global user.name "Luogu Deploy"
    - git config --global user.email "deployer@lohu.info"
    - sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script:
    - hexo clean
    - hexo generate
    - hexo deploy
